import { DemoMachines } from '../../machine/demo/demoMachines';
import { DemoParts } from '../../part/demo/demoParts';
import { IPackingJob } from '../packingJobSlice';

export interface IDemoPackingJob extends IPackingJob {
    step: string;
    demoJob: true;
}

export const DemoJobs: IDemoPackingJob[] = [
    { demoJob: true, step: '1: Choose a part' },
    {
        demoJob: true,
        step: '2: Display Special Instructions & Require Acknowledment (if present)',
        part: DemoParts[0],
    },
    {
        demoJob: true,
        step: "3.1 [part requires 'Final Inspection']: Enter Piece Weight",
        part: DemoParts[0],
        acknowledged: true,
    },
    {
        demoJob: true,
        step: "4.1.1 [part requires 'Final Inspection']: Verify piece weight",
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: false,
    },
    {
        demoJob: true,
        step: "5.1.1 [part requires 'Final Inspection']: Enter Deflash Operator and Machine",
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
    },
    {
        demoJob: true,
        step: "6.1.1 [part requires 'Final Inspection']: Open Job",
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
        operator: 'JK',
        machine: DemoMachines[3],
    },
    {
        demoJob: true,
        step: '7: Enter Lot Quantity',
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
        operator: 'JK',
        machine: DemoMachines[3],
        jobInProgress: true,
    },
    {
        demoJob: true,
        step: '8: Generate Inventory',
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
        operator: 'JK',
        machine: DemoMachines[3],
        jobInProgress: true,
        boxes: 3,
        partialBoxQuantity: 17,
    },
    {
        demoJob: true,
        step: '9: Review Inventory',
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
        operator: 'JK',
        machine: DemoMachines[3],
        jobInProgress: true,
        boxes: 3,
        partialBoxQuantity: 17,
        objectList: [
            {
                serial: 5555123,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555124,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555125,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555126,
                part: DemoParts[0],
                quantity: 17,
                partial: true,
                printed: false,
            },
        ],
    },
    {
        demoJob: true,
        step: '10: Print Labels',
        part: DemoParts[0],
        acknowledged: true,
        quantity: 20,
        pieceWeight: 0.012357,
        validPieceWeight: true,
        operator: 'JK',
        machine: DemoMachines[3],
        jobInProgress: true,
        boxes: 3,
        partialBoxQuantity: 17,
        objectList: [
            {
                serial: 5555123,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555124,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555125,
                part: DemoParts[0],
                quantity: 100,
                partial: false,
                printed: false,
            },
            {
                serial: 5555126,
                part: DemoParts[0],
                quantity: 17,
                partial: true,
                printed: false,
            },
        ],
    },
];
